package dec13Hw41To58;

public class q51To58 {
    //51-A prime number is a natural number greater than 1 that has no positive divisors other than 1
    // and itself.
    //Write a method that checks if a number is a prime number.
    public static void main(String[] args) {

        int num = 29;
        boolean flag = false;
        for (int i = 2; i <= num / 2; ++i) {
            // condition for not prime number
            if (num % i == 0) {
                flag = true;
                break;
            }
        }

        if (!flag)
            System.out.println(num + " is a prime number.");
        else
            System.out.println(num + " is not a prime number.");
    }
    //52-Write a method that returns the sum of all even Fibonacci numbers.
    // Consider all Fibonacci numbers that are less than or equal to n.
    //Each new element in the Fibonacci sequence is generated by adding the previous two elements.
    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
}
